GuildWeb/urls.py
from django.contrib import admin
from django.urls import path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('members/', views.CharacterListView.as_view(), name="members"),
]

app/models.py
import json
import requests
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

client_id = '2a3f57b9e9ca493b9caafdd338853adb'
client_secret = 'aLb4rNxxs2snC8t77vC45gsumqh7yKdK'


class Character(models.Model):
    """
    Clase que define los personajes de los usuarios
    """

    Name = models.CharField(
        max_length=20, help_text="Introduce el nombre del personaje", primary_key=True)

    Realm = models.CharField(
        max_length=20, help_text="Introduce el realm del personaje")

    p_class_choices = [
        ('1', 'Guerrero'),
        ('2', 'Paladin'),
        ('3', 'Cazador'),
        ('4', 'Picaro'),
        ('5', 'Sacerdote'),
        ('7', 'Chaman'),
        ('8', 'Mago'),
        ('9', 'Brujo'),
        ('10', 'Monje'),
        ('11', 'Druida'),
        ('12', 'Cazador de demonios'),
        ('6', 'Caballero de la muerte'),
    ]
    Playable_class = models.CharField(
        max_length=2, choices=p_class_choices, help_text="Introduce la clase del personaje")

    p_race_choices = [
        ('1', 'Humano'),
        ('2', 'Orco'),
        ('3', 'Enano'),
        ('4', 'Elfo de la noche'),
        ('5', 'No-muerto'),
        ('6', 'Tauren'),
        ('7', 'Gnomo'),
        ('8', 'Troll'),
        ('9', 'Goblin'),
        ('10', 'Elfo de sangre'),
        ('11', 'Draenei'),
        ('12', 'Orco equivocado'),
        ('13', 'Continuar'),
        ('14', 'Roto'),
        ('15', 'Esqueleto'),
        ('16', 'Vrykul'),
        ('17', 'Tuskarr'),
        ('18', 'Trol del bosque'),
        ('19', 'Tono'),
        ('20', 'Esqueleto de Rasganorte'),
        ('21', 'Troll de hielo'),
        ('22', 'Huargen'),
        ('23', 'Gilnean'),
        ('24', 'Pandaren'),
        ('25', 'Pandaren'),
        ('26', 'Pandaren'),
        ('27', 'Nocheterna'),
        ('28', 'Tauren de montealto'),
        ('29', 'Elfo del vacío'),
        ('30', 'Draenei forjado por la luz'),
        ('31', 'Troll Zandalari'),
        ('32', 'Kul Tiran'),
        ('33', 'Humano'),
        ('34', 'Enano hierro negro'),
        ('35', 'Vulpera'),
        ('36', 'Orco Maghar'),
        ('37', 'Mecagnomo'),
    ]
    Playable_race = models.CharField(
        max_length=2, choices=p_race_choices, help_text="Introduce la raza del personaje")

    Level = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(120)], default=1, help_text="Introduce el nivel del personaje")

    Avatar_url = models.CharField(
        max_length=200, help_text="URL del Avatar", null=True
    )

    Bust_url = models.CharField(
        max_length=200, help_text="URL del Busto", null=True
    )

    Render_url = models.CharField(
        max_length=200, help_text="URL del Render", null=True
    )

    rank_choices = [
        ('7', 'Iniciado'),
        ('6', 'Alter'),
        ('5', 'Miembro'),
        ('4', 'Veternao'),
        ('3', 'Raider'),
        ('2', 'Alter Oficial'),
        ('1', 'Oficial'),
        ('0', 'GM'),
    ]
    Rank = models.CharField(
        max_length=1, choices=rank_choices, default=7, help_text="Introduce el rango del personaje")

    class Meta:
        ordering = ["Name"]

    def __str__(self):
        return self.Name


class Token(models.Model):
    """
    Clase que define la moneda
    """
    region_choices = [
        ('EU', 'EUROPA'),
        ('US', 'AMERICA')
    ]
    Region = models.CharField(
        max_length=2, choices=region_choices, primary_key=True, default='EU')
    Price = models.IntegerField(default=0)
    Last_update = models.DateTimeField()

    def __str__(self):
        return self.Region

app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from .models import Character

# Create your views here.


def index(request):
    return render(request, 'index.html', context={})


class CharacterListView(generic.ListView):
    model = Character
    template_name = "members.html"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the characters
        context['num_characters'] = Character.objects.all().count()
        context['character_list'] = Character.objects.all()
        return context

app/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>Saurfang Legacy</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- GOOGLE FONTS -->
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <!-- BOOTSTRAP 4 -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <!-- SCROLL REVEAL-->
    <script src="https://unpkg.com/scrollreveal"></script>
    <!-- CSS -->
    {% block style %}
    <link rel="stylesheet" href="{% static 'blog/css/main.css' %}" />
    {% endblock %}
  </head>

  <body>
    <!--NAVIGATION-->
    <nav class="navbar navbar-expand-lg navbar-custom navbar-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand trigger" href="{% url 'index' %}"
          ><img src="{% static 'blog/img/horde_logo.png' %}" alt="" width="40px">SAURFANG LEGACY</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#main">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#info">informacion</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#footer">contacto</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'members' %}">Miembros</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}

    <!-- LANDING PAGE -->
    <section id="main">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-sm-6 my-auto">
            <h2 class="landing-phrase">Lorem ipsum dolor sit.</h2>
            <p class="landing-text">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorum,
              inventore suscipit. Vitae illo numquam aspernatur quos doloribus a
              ducimus, natus, expedita sequi, inventore labore error quod! Odio
              numquam vitae eius!
            </p>
            <div class="vertical-center landing-button">
              <a href="#info" class="btn btn-outline-secondary btn-lg"
                >Read more</a
              >
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- INFO -->
    <div id="info" class="container-fluid" style="padding-top: 60px"></div>

    <section>
      <div class="container mt-5">
        <div class="row">
          <div class="col-md-6">
            <div class="header-content-left">
              <img src="{% static 'blog/img/info1.jpg' %}" alt="" style="width: 100%" />
            </div>
          </div>
          <div class="col-md-6">
            <div class="header-content-right">
              <h1 class="display-4">Lore Ipsum dolor.</h1>
              <p class="mt-5">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae,
                unde molestiae. Impedit iusto perspiciatis a voluptatem at?
                Labore obcaecati, ab fugiat architecto pariatur corrupti
                quibusdam blanditiis nesciunt, enim quod similique!
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- INFO ONE -->
    <section id="info-one">
      <div class="container">
        <div class="row mt-4">
          <div class="col-md-6 my-auto">
            <div class="info-left">
              <h2>Lorem ipsum dolor sit.</h2>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sint
                at temporibus quo magni aliquam impedit assumenda voluptas,
                eligendi fuga tenetur ad consequuntur, omnis porro possimus
                iure. Hic laudantium beatae aperiam.
              </p>
            </div>
          </div>
          <div class="col-md-6">
            <div class="info-right">
              <img src="{% static 'blog/img/info2.jpg' %}" style="width: 100%" />
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- INFO TWO -->
    <section id="info-two">
      <div class="container">
        <div class="row my-4">
          <div class="col-md-6">
            <h2>Lorem ipsum dolor sit.</h2>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque
              nulla id ex, eius voluptatum ipsam earum voluptatibus, molestiae,
              sed iure deleniti consectetur quam distinctio aut! Laudantium
              aspernatur esse nam reiciendis?
            </p>
          </div>
          <div class="col-md-6">
            <h2>Lorem ipsum dolor sit.</h2>
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Dolore
              cupiditate cum soluta culpa harum neque nulla natus voluptatum,
              quam error illum, saepe iusto quaerat excepturi itaque distinctio
              laudantium minus ipsam.
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- FOOTER + CONTACT-->
    <div id="contact" class="container-fluid" style="padding-top: 110px;"></div>

    <footer id="footer">
      <div class="container">
        <div class="row justify-content-center">
          <p id="footer-text">Puedes contactar con nostros uniendote a nuestro servidor de Discord</p>
        </div>
        <div class="row justify-content-center">
          <div class="card">
            <a href="https://discord.gg/AV3VXkF"
              ><img src="{% static 'blog/img/Discord_join.png' %}" alt="" style="width: 100%;"
            /></a>
          </div>
      </div>
    </footer>

    {% endblock %}

  </body>
  <!-- JS, Popper.js, and jQuery -->
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>

  <!-- SCRIPTS -->
  <script>
    ScrollReveal().reveal(".navbar-custom", {
      delay: 1000,
      duration: 2000,
      origin: "bottom",
    });
    ScrollReveal().reveal(".landing-phrase", {
      delay: 1250,
      duration: 2000,
      origin: "bottom",
    });
    ScrollReveal().reveal(".landing-text", {
      delay: 1500,
      duration: 2000,
      origin: "bottom",
    });
    ScrollReveal().reveal(".landing-button", {
      delay: 1750,
      duration: 2000,
      origin: "bottom",
    });
    ScrollReveal().reveal(".header-content-left", {
      duration: 1000,
      delay: 1500,
      origin: "top",
      distance: "300px",
    });
    ScrollReveal().reveal(".header-content-right", {
      duration: 1000,
      delay: 1500,
      origin: "right",
      distance: "300px",
    });
    ScrollReveal().reveal(".info-left", {
      duration: 1000,
      delay: 2000,
      origin: "left",
      distance: "300px",
      viewFactor: 0.2,
    });
    ScrollReveal().reveal(".info-right", {
      duration: 1000,
      delay: 2000,
      origin: "right",
      distance: "300px",
      viewFactor: 0.2,
    });
    ScrollReveal().reveal("#info-two", {
      duration: 1000,
      delay: 2500,
      origin: "bottom",
    });
    ScrollReveal().reveal("#footer-text", {
      duration: 1000,
      delay: 500,
      origin: "bottom",
    });
    ScrollReveal().reveal(".card", {
      duration: 1000,
      delay: 2000,
      origin: "bottom",
    });
    $(window).scroll(function () {
      $("nav").addClass("scrolled", $(this).scrollTop() > 200);
    });
  </script>
</html>

app/templates/members.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>Saurfang Legacy</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- GOOGLE FONTS -->
    <link
      href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
      rel="stylesheet"
    />
    <!-- BOOTSTRAP 4 -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <!-- SCROLL REVEAL-->
    <script src="https://unpkg.com/scrollreveal"></script>
    <!-- CSS -->
    {% block style %}
    <link rel="stylesheet" href="{% static 'blog/css/members.css' %}" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
    {% endblock %}
  </head>

  <body>
    <!--NAVIGATION-->
    <nav class="navbar navbar-expand-lg navbar-custom navbar-dark fixed-top">
      <div class="container-fluid">
        <a class="navbar-brand trigger" href="{% url 'index' %}"
          ><img src="/static/blog/img/horde_logo.png" alt="" width="40px" />SAURFANG
          LEGACY</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}#main">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}#info">informacion</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'index' %}#footer">contacto</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'members' %}">Miembros</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container" style="margin-top: 110px; margin-bottom: 20px;">
      <div style="margin-bottom: 10px;">
        <h2>Actualmente la Guild cuenta con {{ num_characters }} personajes.</h2>
      </div>
      <div class="row">
        <div class="input-group">
          <input
            id="filtro"
            class="form-control"
            type="text"
            placeholder="¿Buscas algún personaje en específico?"
          />
          <div class="input-group-append">
            <button id="search" class="btn btn-primary" type="submit">Buscar</button>
          </div>
        </div>
      </div>
    </div>

    <div class="container-fluid" style="width: 80%;">
      {% if character_list %}
      <table
      id="character"
      class="table table-striped table-bordered table-sm"
      cellspacing="0"
      width="100%"
    >
      <thead>
        <tr>
            <th class="th-sm">Nombre</th>
            <th class="th-sm">Clase</th>
            <th class="th-sm">Nivel</th>
            <th class="th-sm">Rango</th>
            <th class="th-sm">Servidor</th>
        </tr>
      </thead>
      <tbody>
        {% for Character in character_list %}
            <tr>
                <td>
                    <a href="https://worldofwarcraft.com/es-es/character/eu/{{ Character.Realm }}/{{ Character.Name }}/" target="blank">
                        <img src="{{ Character.Avatar_url }}" alt=""/>{{ Character.Name }}
                    </a>
                </td>
              <td class="td-align">{{ Character.get_Playable_class_display}}</td>
              <td class="td-align">{{ Character.Level}}</td>
              <td class="td-align">{{ Character.get_Rank_display}}</td>
              <td class="td-align">{{ Character.Realm }}</td>
            </tr>
            {% endfor %}
      </tbody>
      <tfoot>
      </tfoot>
    </table>
      {% else %}
      <h2 style="text-align: center">
        No se ha podido establecer la conexión con la base de datos, lo
        sentimos.
      </h2>
      {% endif %}
    </div>
  </body>

  <!-- JS, Popper.js, and jQuery -->
  <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
  ></script>
  <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>

  <!-- SCRIPTS -->
  <script>
    $(document).ready(function () {
      $("nav").addClass("animated");
    });

    //Datatables
    $(document).ready( function () {
        var table = $('#character').DataTable({
        "dom": '<"top"i>rt<"bottom"><"clear">',
        "paging": false,
        "bInfo" : false,
    });
    $('#filtro').on( 'keyup click', function () {
        table.search($('#filtro').val()).draw();
        } );
    } );

  </script>
</html>